---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s
  labels:
    app: hello-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-k8s
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
      - name: hello-k8s
        image: diablinux/hello-k8s:latest
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
        ports:
        - name: http-api
          containerPort: 5000
